export enum ProgrammingLanguage {
    JavaScript = 'JavaScript',
    Python = 'Python',
    Java = 'Java',
    CPP = 'C++',
    CSharp = 'C#',
    Ruby = 'Ruby',
    PHP = 'PHP',
    HTML = 'HTML',
    CSS = 'CSS',
    Swift = 'Swift',
    Go = 'Go',
    Rust = 'Rust',
    TypeScript = 'TypeScript',
}